timezone: UTC
encoding: utf-8
exclude: ["vendor"]
redcarpet:
  extensions: [smart]
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
